insert into acc_coa(code,name) values("0001","FREEHOLD COST");
insert into acc_coa(code,name) values("0020E","PLANT ELLAND");
insert into acc_coa(code,name) values("0020R","PLANT RAVENSTHORPE");
insert into acc_coa(code,name) values("0030H","OFFICE EQUIP HONLEY");
insert into acc_coa(code,name) values("0031","PREMISES - Storage Yard");
insert into acc_coa(code,name) values("0040E","FURN & FIX ELLAND");
insert into acc_coa(code,name) values("0040R","FURN & FIX RAVENSTHORPE");
insert into acc_coa(code,name) values("0050H","MOTOR VEHICLES HONLEY");
insert into acc_coa(code,name) values("0100","WORKSHOP EQUIPMENT");
insert into acc_coa(code,name) values("0100L","WORKSHOP EQUIP LEEDS RD");
insert into acc_coa(code,name) values("0102","PRINTING MACHINERY");
insert into acc_coa(code,name) values("0200E","HIRE FLEET COST ELLAND");
insert into acc_coa(code,name) values("0200R","HIRE FLEET COST RAVENSTHORPE");
insert into acc_coa(code,name) values("0301","F/F DEPRECIATION");
insert into acc_coa(code,name) values("0410","SALE OF VEHICLES");
insert into acc_coa(code,name) values("0500H","COMPUTER EQUIP HONLEY");
insert into acc_coa(code,name) values("0501","DEPRECATION COMP.EQUIP.");
insert into acc_coa(code,name) values("1001H","STOCK HONLEY");
insert into acc_coa(code,name) values("1099","BAD DEBT PROVISION");
insert into acc_coa(code,name) values("1103","Prepayments");
insert into acc_coa(code,name) values("1201","NATWEST A/C");
insert into acc_coa(code,name) values("1206","DIRECTORS LOAN AJ");
insert into acc_coa(code,name) values("1230","Petty Cash");
insert into acc_coa(code,name) values("1240","FLOATS");
insert into acc_coa(code,name) values("2102","OTHER CREDITORS");
insert into acc_coa(code,name) values("2200","Sales VAT Control Account");
insert into acc_coa(code,name) values("2203","VAT SUSPENSE");
insert into acc_coa(code,name) values("2210H","PAYE HONLEY");
insert into acc_coa(code,name) values("2211","National Insurance");
insert into acc_coa(code,name) values("2211L","NATIONAL INSURANCE LEEDS RD");
insert into acc_coa(code,name) values("2300","Loans");
insert into acc_coa(code,name) values("2300L","LOAN LEEDS RD");
insert into acc_coa(code,name) values("2310E","HP ELLAND");
insert into acc_coa(code,name) values("2310R","HP RAVENSTHORPE");
insert into acc_coa(code,name) values("2330","ACT RECOVERABLE");
insert into acc_coa(code,name) values("3100","REVALUATION RESERVE");
insert into acc_coa(code,name) values("3200E","P & L ELLAND");
insert into acc_coa(code,name) values("3200R","P & L RAVENSTHORPE");
insert into acc_coa(code,name) values("4000H","SALES HONLEY");
insert into acc_coa(code,name) values("4001","HIRE");
insert into acc_coa(code,name) values("4001L","HIRE LEEDS RD");
insert into acc_coa(code,name) values("4002E","RE-HIRE ELLAND");
insert into acc_coa(code,name) values("4002R","RE-HIRE RAVENSTHORPE");
insert into acc_coa(code,name) values("4003H","LABOUR HONLEY");
insert into acc_coa(code,name) values("4004","SAFETY TESTS");
insert into acc_coa(code,name) values("4004L","Safety Tests Leeds Rd");
insert into acc_coa(code,name) values("4005E","TRANSPORT ELLAND");
insert into acc_coa(code,name) values("4005R","TRANSPORT RAVENSTHORPE");
insert into acc_coa(code,name) values("4006H","Damage waiver/Insurance");
insert into acc_coa(code,name) values("4009","Discounts Allowed");
insert into acc_coa(code,name) values("4009L","DISCOUNTS ALLOWED LEEDS RD");
insert into acc_coa(code,name) values("4200E","SALE OF ASSETS ELLAND");
insert into acc_coa(code,name) values("4200R","SALE OF ASSETS RAVENSTHORPE");
insert into acc_coa(code,name) values("4900H","MISC INCOME HONLEY");
insert into acc_coa(code,name) values("4903","INSURANCE CLAIMS");
insert into acc_coa(code,name) values("5000E","MATERIALS PURCHASE ELLAND");
insert into acc_coa(code,name) values("5000R","MATERIALS PURCHASE RAVENSTHPE");
insert into acc_coa(code,name) values("5001H","MACHINES ON LEASE HONLEY");
insert into acc_coa(code,name) values("5003","CUSTOMER REPAIRS");
insert into acc_coa(code,name) values("5009E","DISCOUNTS TAKEN ELLAND");
insert into acc_coa(code,name) values("5009R","DISCOUNTS TAKEN RAVENSTHORPE");
insert into acc_coa(code,name) values("5100H","CARRIAGE OUT HONLEY");
insert into acc_coa(code,name) values("5102","TRANSPORT INSURANCE");
insert into acc_coa(code,name) values("5200H","OPENING STOCK HONLEY");
insert into acc_coa(code,name) values("5201","CLOSING STOCK");
insert into acc_coa(code,name) values("5201L","CLOSING STOCK LEEDS RD");
insert into acc_coa(code,name) values("6201","Advertising");
insert into acc_coa(code,name) values("6201L","ADVERTISING LEEDS RD");
insert into acc_coa(code,name) values("6900E","MISC ELLAND");
insert into acc_coa(code,name) values("6900R","MISC EXPENSES RAVENSTHORPE");
insert into acc_coa(code,name) values("7004","Wages - Regular");
insert into acc_coa(code,name) values("7004L","WAGES LEEDS RD");
insert into acc_coa(code,name) values("7006","EMPLOYERS N.I.");
insert into acc_coa(code,name) values("7007H","PENSION HONLEY");
insert into acc_coa(code,name) values("7009","MEDICAL SCHEME SUBS");
insert into acc_coa(code,name) values("7100H","RENT HONLEY");
insert into acc_coa(code,name) values("7102","Water Rates");
insert into acc_coa(code,name) values("7102L","WATER RATES LEEDS RD");
insert into acc_coa(code,name) values("7103E","GENERAL RATES ELLAND");
insert into acc_coa(code,name) values("7103R","GENERAL RATES RAVENSTHORPE");
insert into acc_coa(code,name) values("7104H","PREMISES INSURANCE HONLEY");
insert into acc_coa(code,name) values("7200","Electricity");
insert into acc_coa(code,name) values("7200L","ELECTRIC LEEDS R");
insert into acc_coa(code,name) values("7202","Oil");
insert into acc_coa(code,name) values("7300H","FUEL ETC HONLEY");
insert into acc_coa(code,name) values("7301","Repairs & Service Motor");
insert into acc_coa(code,name) values("7301L","MOTOR REPAIRS ETC LEEDS RD");
insert into acc_coa(code,name) values("7303","Vehicle Insurance");
insert into acc_coa(code,name) values("7303L","MOTOR INS & TAX LEEDS RD");
insert into acc_coa(code,name) values("7305","CAR EXPENSES");
insert into acc_coa(code,name) values("7401E","CAR HIRE ELLAND");
insert into acc_coa(code,name) values("7401R","CAR HIRE RAVENSTHORPE");
insert into acc_coa(code,name) values("7402H","TRAVEL HONLEY");
insert into acc_coa(code,name) values("7403","U.K. Entertainment");
insert into acc_coa(code,name) values("7499","STATIONERY");
insert into acc_coa(code,name) values("7500H","PRINTING HONLEY");
insert into acc_coa(code,name) values("7501","Postage And Carriage");
insert into acc_coa(code,name) values("7501L","POSTAGE LEEDS RD");
insert into acc_coa(code,name) values("7502E","PHONE ELLAND");
insert into acc_coa(code,name) values("7502M","MOBILES TO DISTRIBUTE");
insert into acc_coa(code,name) values("7504","Office Stationery");
insert into acc_coa(code,name) values("7504L","OFFICE STATIONERY LEEDS RD");
insert into acc_coa(code,name) values("7507","COMPUTER/OFFICE EQ. MTCE.");
insert into acc_coa(code,name) values("7507L","COMP/OFFICE EQUIP MAINT.LDSRD");
insert into acc_coa(code,name) values("7600E","LEGAL FEES ELLAND");
insert into acc_coa(code,name) values("7600R","LEGAL FEES RAVENSTHORPE");
insert into acc_coa(code,name) values("7601H","ACCOUNTANCY FEES HONLEY");
insert into acc_coa(code,name) values("7603","Professional Fees");
insert into acc_coa(code,name) values("7603L","PROF FEES LEEDS RD");
insert into acc_coa(code,name) values("7700E","EQUIP HIRE ELLAND");
insert into acc_coa(code,name) values("7700R","EQUIP HIRE RAVENSTHORPE");
insert into acc_coa(code,name) values("7702E","SCAFFOLD HIRE ELLAND");
insert into acc_coa(code,name) values("7702R","SCAFFOLD HIRE RAVENSTHORPE");
insert into acc_coa(code,name) values("7800H","FLEET REPAIRS ETC HONLEY");
insert into acc_coa(code,name) values("7801","Cleaning");
insert into acc_coa(code,name) values("7801L","CLEANING LEEDS RD");
insert into acc_coa(code,name) values("7803E","PREMISES EXP ELLAND");
insert into acc_coa(code,name) values("7803R","PREMISES EXP RAVENSTHORPE");
insert into acc_coa(code,name) values("7900H","BANK INTEREST HONLEY");
insert into acc_coa(code,name) values("7901","Bank Charges");
insert into acc_coa(code,name) values("7901L","BANK CHARGES LEEDS RD");
insert into acc_coa(code,name) values("7904","H.P. INTEREST");
insert into acc_coa(code,name) values("7905H","CREDIT CHARGE HONLEY");
insert into acc_coa(code,name) values("7906","AMERICAN EXPRESS DISCOUNT");
insert into acc_coa(code,name) values("7906L","AMEX DISC LEEDS RD");
insert into acc_coa(code,name) values("8001","HIRE FLEET DEPRECIATION");
insert into acc_coa(code,name) values("8004","OFFICE EQUIPMENT DEPR.");
insert into acc_coa(code,name) values("8200","DONATIONS");
insert into acc_coa(code,name) values("8200L","DONATIONS LEEDS RD");
insert into acc_coa(code,name) values("8201E","SUBS ELLAND");
insert into acc_coa(code,name) values("8201R","SUBS RAVENSTHORPE");
insert into acc_coa(code,name) values("8203H","TRAINING HONLEY");
insert into acc_coa(code,name) values("8204","FLEET INSURANCE");
insert into acc_coa(code,name) values("8204L","FLEET INSURANCE LEEDS RD");
insert into acc_coa(code,name) values("8205E","REFRESHMENTS ELLAND");
insert into acc_coa(code,name) values("8205R","REFRESHMENTS RAVENSTHORPE");
insert into acc_coa(code,name) values("8206H","INSURANCE (ADD) HONLEY");
insert into acc_coa(code,name) values("8207","RAPID TOOLS DIRECT");
insert into acc_coa(code,name) values("99999999","Non posting account");
insert into acc_coa(code,name) values("0020","Plant & Machinery");
insert into acc_coa(code,name) values("0020L","PLANT LEEDS RD");
insert into acc_coa(code,name) values("0030E","OFFICE EQUIP ELLAND");
insert into acc_coa(code,name) values("0030R","OFFICE EQUIP RAVENSTHORPE");
insert into acc_coa(code,name) values("0040","Furniture & Fixtures");
insert into acc_coa(code,name) values("0040L","FURN & FIX LEEDS RD");
insert into acc_coa(code,name) values("0050E","MOTOR VEHICLES ELLAND");
insert into acc_coa(code,name) values("0050R","MOTOR VEHICLES RAVENSTHORPE");
insert into acc_coa(code,name) values("0100H","WORKSHOP EQUIP HONLEY");
insert into acc_coa(code,name) values("0101","WORKSHOP EQ DEPRECIATION");
insert into acc_coa(code,name) values("0200","HIRE FLEET COST");
insert into acc_coa(code,name) values("0200L","HIRE FLEET COST LEEDS RD");
insert into acc_coa(code,name) values("0300","F/F COST");
insert into acc_coa(code,name) values("0403","VEHICLE DEPRECIATION");
insert into acc_coa(code,name) values("0500E","COMPUTER EQUIP ELLAND");
insert into acc_coa(code,name) values("0500R","COMPUTER EQUIP RAVENSTHORPE");
insert into acc_coa(code,name) values("1001E","STOCK ELLAND");
insert into acc_coa(code,name) values("1001R","STOCK RAVENSTHORPE");
insert into acc_coa(code,name) values("1102","RENT DEPOSIT AC");
insert into acc_coa(code,name) values("1200","LLOYDS A/C");
insert into acc_coa(code,name) values("1205","DIRECTOR LOAN KS");
insert into acc_coa(code,name) values("1220","PAYPAL");
insert into acc_coa(code,name) values("1236","BANK LOAN INTEREST");
insert into acc_coa(code,name) values("2101","SUNDRY CREDITORS");
insert into acc_coa(code,name) values("2199","VAT on Puchases");
insert into acc_coa(code,name) values("2202","VAT Liability");
insert into acc_coa(code,name) values("2210E","PAYE ELLAND");
insert into acc_coa(code,name) values("2210R","PAYE RAVENSTHORPE");
insert into acc_coa(code,name) values("2211H","NATIONAL INSURANCE HONLEY");
insert into acc_coa(code,name) values("2220","Net Wages");
insert into acc_coa(code,name) values("2300H","LOAN HONLEY");
insert into acc_coa(code,name) values("2310","Hire Purchase");
insert into acc_coa(code,name) values("2310L","HP LEEDS RD");
insert into acc_coa(code,name) values("2320","CORPORATION TAX");
insert into acc_coa(code,name) values("3001","PREFERENCE SHARES");
insert into acc_coa(code,name) values("3200","Profit & Loss Account");
insert into acc_coa(code,name) values("3200L","P & L LEEDS RD");
insert into acc_coa(code,name) values("4000E","SALES ELLAND");
insert into acc_coa(code,name) values("4000R","SALES RAVENSTHORPE");
insert into acc_coa(code,name) values("4001H","HIRE HONLEY");
insert into acc_coa(code,name) values("4002","RE-HIRE");
insert into acc_coa(code,name) values("4002L","RE-HIRE LEEDS RD");
insert into acc_coa(code,name) values("4003E","LABOUR ELLAND");
insert into acc_coa(code,name) values("4003R","LABOUR RAVENSTHORPE");
insert into acc_coa(code,name) values("4004H","Safety Tests Honley");
insert into acc_coa(code,name) values("4005","TRANSPORT");
insert into acc_coa(code,name) values("4005L","TRANSPORT LEEDS RD");
insert into acc_coa(code,name) values("4006E","Damage waiver/Insurance");
insert into acc_coa(code,name) values("4006R","DAMAGE WAIVER/INSURANCE");
insert into acc_coa(code,name) values("4009H","DISCOUNTS ALLOWED HONLEY");
insert into acc_coa(code,name) values("4200","SALES OF ASSETS");
insert into acc_coa(code,name) values("4200L","Sale of Assets Leeds Road");
insert into acc_coa(code,name) values("4900E","MISC INCOME ELLAND");
insert into acc_coa(code,name) values("4900R","MISC INCOME RAVENSTHORPE");
insert into acc_coa(code,name) values("5000","Materials Purchases");
insert into acc_coa(code,name) values("5000L","MATERIALS PURCHASE LEEDS RD");
insert into acc_coa(code,name) values("5001E","MACHINES ON LEASE ELLAND");
insert into acc_coa(code,name) values("5002","Miscellaneous Purchases");
insert into acc_coa(code,name) values("5009","DISCOUNTS TAKEN");
insert into acc_coa(code,name) values("5009L","DISCOUNTS TAKEN LEEDS RD");
insert into acc_coa(code,name) values("5100E","CARRIAGE OUT ELLAND");
insert into acc_coa(code,name) values("5100R","CARRIAGE OUT RAVENSTHORPE");
insert into acc_coa(code,name) values("5200E","OPENING STOCK ELLAND");
insert into acc_coa(code,name) values("5200R","OPENING STOCK RAVENSTHORPE");
insert into acc_coa(code,name) values("5201H","CLOSING STOCK HONLEY");
insert into acc_coa(code,name) values("6200","Sales Promotions");
insert into acc_coa(code,name) values("6201H","ADVERTISING HONLEY");
insert into acc_coa(code,name) values("6900","Miscellaneous Expenses");
insert into acc_coa(code,name) values("6900L","MISC LEEDS ROAD");
insert into acc_coa(code,name) values("7003","STAFF SALARIES");
insert into acc_coa(code,name) values("7004H","WAGES HONLEY");
insert into acc_coa(code,name) values("7005","PENSION FUND");
insert into acc_coa(code,name) values("7007E","PENSION ELLAND");
insert into acc_coa(code,name) values("7007R","PENSION RAVENSTHORPE");
insert into acc_coa(code,name) values("7100E","RENT ELLAND");
insert into acc_coa(code,name) values("7100R","RENT RAVENSTHORPE");
insert into acc_coa(code,name) values("7102H","WATER RATES HONLEY");
insert into acc_coa(code,name) values("7103","General Rates");
insert into acc_coa(code,name) values("7103L","GENERAL RATES LEEDS RD");
insert into acc_coa(code,name) values("7104E","PREMISES INSURANCE ELLAND");
insert into acc_coa(code,name) values("7104R","PREMISES INSURANCE RAVENSTHORP");
insert into acc_coa(code,name) values("7200H","ELECTRIC HONLEY");
insert into acc_coa(code,name) values("7201","GAS");
insert into acc_coa(code,name) values("7300E","FUEL ETC ELLAND");
insert into acc_coa(code,name) values("7300R","FUEL ETC RAVENSTHORPE");
insert into acc_coa(code,name) values("7301H","MOTOR REPAIRS ETC HONLEY");
insert into acc_coa(code,name) values("7302","Licences");
insert into acc_coa(code,name) values("7303H","MOTOR INS & TAX HONLEY");
insert into acc_coa(code,name) values("7304","VAN EXPENSES");
insert into acc_coa(code,name) values("7401","CAR HIRE");
insert into acc_coa(code,name) values("7401L","CAR HIRE LEEDS RD");
insert into acc_coa(code,name) values("7402E","TRAVEL ELLAND");
insert into acc_coa(code,name) values("7402R","TRAVEL RAVENSTHORPE");
insert into acc_coa(code,name) values("7407","HOME OFFICE EXPENSES");
insert into acc_coa(code,name) values("7500E","PRINTING ELLAND");
insert into acc_coa(code,name) values("7500R","PRINTING RAVENSTHORPE");
insert into acc_coa(code,name) values("7501H","POSTAGE HONLEY");
insert into acc_coa(code,name) values("7502","Telephone");
insert into acc_coa(code,name) values("7502L","PHONES LEEDS RD");
insert into acc_coa(code,name) values("7503","FACSIMILE");
insert into acc_coa(code,name) values("7504H","OFFICE STATIONERY HONLEY");
insert into acc_coa(code,name) values("7506","COMPUTER ACCESSORIES");
insert into acc_coa(code,name) values("7507H","COMP/OFFICE EQUIP MAINT HONLEY");
insert into acc_coa(code,name) values("7600","Legal Fees");
insert into acc_coa(code,name) values("7600L","LEGAL FEES LEEDS RD");
insert into acc_coa(code,name) values("7601E","ACCOUNTANCY FEES ELLAND");
insert into acc_coa(code,name) values("7601R","ACCOUNTANCY FEES RAVENSTHORPE");
insert into acc_coa(code,name) values("7603H","PROF FEES HONLEY");
insert into acc_coa(code,name) values("7700","Equipment Hire");
insert into acc_coa(code,name) values("7700L","EQUIP HIRE LEEDS RD");
insert into acc_coa(code,name) values("7702","Scaffold Hire");
insert into acc_coa(code,name) values("7702L","SCAFFOLD HIRE LEEDS RD");
insert into acc_coa(code,name) values("7800E","FLEET REPAIRS ETC ELLAND");
insert into acc_coa(code,name) values("7800R","FLEET REPAIRS ETC RAVENSTHORPE");
insert into acc_coa(code,name) values("7801H","CLEANING HONLEY");
insert into acc_coa(code,name) values("7803","Premises Expenses (misc)");
insert into acc_coa(code,name) values("7803L","PREMISES EXP LEEDS RD");
insert into acc_coa(code,name) values("7900E","BANK INTEREST ELLAND");
insert into acc_coa(code,name) values("7900R","BANK INTEREST RAVENSTHORPE");
insert into acc_coa(code,name) values("7901H","BANK CHARGES HONLEY");
insert into acc_coa(code,name) values("7902","Royal Bank Finance Chargs");
insert into acc_coa(code,name) values("7905E","CREDIT CHARGE ELLAND");
insert into acc_coa(code,name) values("7905R","CREDIT CHARGE RAVENSTHORPE");
insert into acc_coa(code,name) values("7906H","AMEX DISC HONLEY");
insert into acc_coa(code,name) values("8000","COMPUTER DEPRECIATION");
insert into acc_coa(code,name) values("8003","VEHICLE DEPRECIATION");
insert into acc_coa(code,name) values("8100","Bad Debt Write Off");
insert into acc_coa(code,name) values("8200H","DONATIONS HONLEY");
insert into acc_coa(code,name) values("8201","Subscriptions");
insert into acc_coa(code,name) values("8201L","SUBS LEEDS RD");
insert into acc_coa(code,name) values("8203E","TRAINING ELLAND");
insert into acc_coa(code,name) values("8203R","TRAINING RAVENSTHORPE");
insert into acc_coa(code,name) values("8204H","FLEET INSURANCE HONLEY");
insert into acc_coa(code,name) values("8205","Refreshments");
insert into acc_coa(code,name) values("8205L","REFRESHMENTS LEEDS RD");
insert into acc_coa(code,name) values("8206E","INSURANCE (ADD) ELLAND");
insert into acc_coa(code,name) values("8206R","INSURANCE (ADD) RAVENSTHORPE");
insert into acc_coa(code,name) values("9999","Mispostings Account");
insert into acc_coa(code,name) values("0010","FREEHOLD PROPERTY");
insert into acc_coa(code,name) values("0020H","PLANT HONLEY");
insert into acc_coa(code,name) values("0030","Office Equipment");
insert into acc_coa(code,name) values("0030L","OFFICE EQUIP LEEDS RD");
insert into acc_coa(code,name) values("0032","DEPRECIATION - Storage Yard");
insert into acc_coa(code,name) values("0040H","FURN & FIX HONLEY");
insert into acc_coa(code,name) values("0050","Motor Vehicles");
insert into acc_coa(code,name) values("0050L","MOTOR VEHICLES LEEDS RD");
insert into acc_coa(code,name) values("0100E","WORKSHOP EQUIP ELLAND");
insert into acc_coa(code,name) values("0100R","WORKSHOP EQUIP RAVENSTHORPE");
insert into acc_coa(code,name) values("0103","PRINTING DEPRECIATION");
insert into acc_coa(code,name) values("0200H","HIRE FLEET COST HONLEY");
insert into acc_coa(code,name) values("0201","H/F DEPRECIATION");
insert into acc_coa(code,name) values("0402","VEHICLE COST");
insert into acc_coa(code,name) values("0500","COMPUTER EQUIPMENT");
insert into acc_coa(code,name) values("0500L","COMPUTER EQUIP LEEDS RD");
insert into acc_coa(code,name) values("1001","Stock");
insert into acc_coa(code,name) values("1001L","STOCK LEEDS RD");
insert into acc_coa(code,name) values("1100","Debtors Control Account");
insert into acc_coa(code,name) values("1104","CASH DEBTORS");
insert into acc_coa(code,name) values("1204","BANK ACCOUNT (RESERVE)");
insert into acc_coa(code,name) values("1210","Royal Bank Finance");
insert into acc_coa(code,name) values("1235","AMERICAN EXPRESS");
insert into acc_coa(code,name) values("2100","Creditors Control Account");
insert into acc_coa(code,name) values("2109","ACCRUALS");
insert into acc_coa(code,name) values("2201","Purchases VAT Control Acc");
insert into acc_coa(code,name) values("2210","P.A.Y.E.");
insert into acc_coa(code,name) values("2210L","PAYE LEEDS RD");
insert into acc_coa(code,name) values("2211E","NATIONAL INSURANCE ELLAND");
insert into acc_coa(code,name) values("2211R","NATIONAL INS RAVENSTHORPE");
insert into acc_coa(code,name) values("2300E","LOAN ELLAND");
insert into acc_coa(code,name) values("2300R","LOAN RAVENSTHORPE");
insert into acc_coa(code,name) values("2310H","HP HONLEY");
insert into acc_coa(code,name) values("2315","DEFERRED TAX");
insert into acc_coa(code,name) values("3000","SHARE CAPITAL");
insert into acc_coa(code,name) values("3101","UNDISTRIBUTED RESERVES");
insert into acc_coa(code,name) values("3200H","P & L HONLEY");
insert into acc_coa(code,name) values("4000","SALES");
insert into acc_coa(code,name) values("4000L","SALES LEEDS RD");
insert into acc_coa(code,name) values("4001E","HIRE ELLAND");
insert into acc_coa(code,name) values("4001R","HIRE RAVENSTHORPE");
insert into acc_coa(code,name) values("4002H","RE-HIRE HONLEY");
insert into acc_coa(code,name) values("4003","LABOUR");
insert into acc_coa(code,name) values("4003L","LABOUR LEEDS RD");
insert into acc_coa(code,name) values("4004E","Safety Tests Elland");
insert into acc_coa(code,name) values("4004R","SAFETY TESTS Ravensthorpe");
insert into acc_coa(code,name) values("4005H","TRANSPORT HONLEY");
insert into acc_coa(code,name) values("4006","DAMAGE WAIVER");
insert into acc_coa(code,name) values("4006L","Damage waiver/Insurance");
insert into acc_coa(code,name) values("4009E","DISCOUNTS ALLOWED ELLAND");
insert into acc_coa(code,name) values("4009R","DISCOUNTS ALLOWED RAVENSTHORPE");
insert into acc_coa(code,name) values("4200H","Sale of Assets Honley");
insert into acc_coa(code,name) values("4900","MISCELLANEOUS INCOME");
insert into acc_coa(code,name) values("4900L","MISC INCOME LEEDS RD");
insert into acc_coa(code,name) values("4904","RENT DEPOSIT");
insert into acc_coa(code,name) values("5000H","MATERIALS PURCHASE HONLEY");
insert into acc_coa(code,name) values("5001","MACHINES ON LEASE");
insert into acc_coa(code,name) values("5001L","MACHINES ON LEASE LDS RD");
insert into acc_coa(code,name) values("5004","SUNDRY");
insert into acc_coa(code,name) values("5009H","DISCOUNTS TAKEN HONLEY");
insert into acc_coa(code,name) values("5100","CARRIAGE OUT");
insert into acc_coa(code,name) values("5100L","CARRIAGE OUT LEEDS RD");
insert into acc_coa(code,name) values("5200","OPENING STOCK");
insert into acc_coa(code,name) values("5200L","OPENING STOCK LEEDS RD");
insert into acc_coa(code,name) values("5201E","CLOSING STOCK ELLAND");
insert into acc_coa(code,name) values("5201R","CLOSING STOCK RAVENSTHORPE");
insert into acc_coa(code,name) values("6201E","ADVERTISING ELLAND");
insert into acc_coa(code,name) values("6201R","ADVERTISING RAVENSTHORPE");
insert into acc_coa(code,name) values("6900H","MISC HONLEY");
insert into acc_coa(code,name) values("7002","DIRECTORS REMUNERATION");
insert into acc_coa(code,name) values("7004E","WAGES ELLAND");
insert into acc_coa(code,name) values("7004R","WAGES RAVENSTHORPE");
insert into acc_coa(code,name) values("7007","Pension Fund Payments");
insert into acc_coa(code,name) values("7007L","PENSION LEEDS RD");
insert into acc_coa(code,name) values("7100","Rent");
insert into acc_coa(code,name) values("7100L","RENT LEEDS RD");
insert into acc_coa(code,name) values("7102E","WATER RATES ELLAND");
insert into acc_coa(code,name) values("7102R","WATER RATES RAVENSTHORPE");
insert into acc_coa(code,name) values("7103H","GENERAL RATES HONLEY");
insert into acc_coa(code,name) values("7104","Premises Insurance");
insert into acc_coa(code,name) values("7104L","PREMISES INSURANCE LEEDS RD");
insert into acc_coa(code,name) values("7200E","ELECTRIC ELLAND");
insert into acc_coa(code,name) values("7200R","ELECTRIC RAVENSTHORPE");
insert into acc_coa(code,name) values("7300","Fuel & Oil Motor");
insert into acc_coa(code,name) values("7300L","FUEL ETC LEEDS RD");
insert into acc_coa(code,name) values("7301E","MOTOR REPAIRS ETC ELLAND");
insert into acc_coa(code,name) values("7301R","MOTOR REPAIRS ETC RAVENSTHORPE");
insert into acc_coa(code,name) values("7303E","MOTOR INS & TAX ELLAND");
insert into acc_coa(code,name) values("7303R","MOTOR INS & TAX RAVENSTHORPE");
insert into acc_coa(code,name) values("7306","CAR MILEAGE ALLOWANCE");
insert into acc_coa(code,name) values("7401H","CAR HIRE HONLEY");
insert into acc_coa(code,name) values("7402","TRAVELLING (Incl. Hotels)");
insert into acc_coa(code,name) values("7402L","TRAVEL LEEDS RD");
insert into acc_coa(code,name) values("7406","SUBSISTENCE");
insert into acc_coa(code,name) values("7500","Printing");
insert into acc_coa(code,name) values("7500L","PRINTING LEEDS RD");
insert into acc_coa(code,name) values("7501E","POSTAGE ELLAND");
insert into acc_coa(code,name) values("7501R","POSTAGE RAVENSTHORPE");
insert into acc_coa(code,name) values("7502H","PHONES HONLEY");
insert into acc_coa(code,name) values("7502R","PHONES RAVENSTHORPE");
insert into acc_coa(code,name) values("7504E","OFFICE STATIONERY ELLAND");
insert into acc_coa(code,name) values("7504R","OFFIC STATIONERY RAVENSTHORPE");
insert into acc_coa(code,name) values("7507E","COMP/OFFICE EQUIP MAINT ELLAND");
insert into acc_coa(code,name) values("7507R","COMP/OFF EQP.MAINT.RAVENS");
insert into acc_coa(code,name) values("7600H","LEGAL FEES HONLEY");
insert into acc_coa(code,name) values("7601","Audit & Accountancy Fees");
insert into acc_coa(code,name) values("7601L","ACCOUNTANCY FEES LEEDS RD");
insert into acc_coa(code,name) values("7603E","PROF FEES ELLAND");
insert into acc_coa(code,name) values("7603R","PROF FEES RAVENSTHORPE");
insert into acc_coa(code,name) values("7700H","EQUIP HIRE HONLEY");
insert into acc_coa(code,name) values("7701","OFFICE MACHINE MAINT.");
insert into acc_coa(code,name) values("7702H","SCAFFOLD HIRE HONLEY");
insert into acc_coa(code,name) values("7800","Repairs And Renewals");
insert into acc_coa(code,name) values("7800L","FLEET REPAIRS ETC LEEDS RD");
insert into acc_coa(code,name) values("7801E","CLEANING ELLAND");
insert into acc_coa(code,name) values("7801R","CLEANING RAVENSTHORPE");
insert into acc_coa(code,name) values("7803H","PREMISES EXP HONLEY");
insert into acc_coa(code,name) values("7900","Bank Interest Paid");
insert into acc_coa(code,name) values("7900L","BANK INTEREST LEEDS RD");
insert into acc_coa(code,name) values("7901E","BANK CHARGES ELLAND");
insert into acc_coa(code,name) values("7901R","BANK CHARGES RAVENSTHORPE");
insert into acc_coa(code,name) values("7905","CREDIT CHARGES");
insert into acc_coa(code,name) values("7905L","CREDIT CHARGE LEEDS RD");
insert into acc_coa(code,name) values("7906E","AMEX DISC ELLAND");
insert into acc_coa(code,name) values("7906R","AMEX DISC RAVENSTHORPE");
insert into acc_coa(code,name) values("8002","FURNITURE/FIX/FITTINGS DP");
insert into acc_coa(code,name) values("8005","DEPRECIATION - LEASES");
insert into acc_coa(code,name) values("8200E","DONATIONS ELLAND");
insert into acc_coa(code,name) values("8200R","DONATIONS RAVENSTHORPE");
insert into acc_coa(code,name) values("8201H","SUBS HONLEY");
insert into acc_coa(code,name) values("8203","TRAINING COSTS");
insert into acc_coa(code,name) values("8203L","TRAINING LEEDS RD");
insert into acc_coa(code,name) values("8204E","FLEET INSURANCE ELLAND");
insert into acc_coa(code,name) values("8204R","FLEET INS RAVENSTHORPE");
insert into acc_coa(code,name) values("8205H","REFRESHMENTS HONLEY");
insert into acc_coa(code,name) values("8206","INSURANCE (Additional)");
insert into acc_coa(code,name) values("8206L","INSURANCE (ADD) LEEDS RD");
insert into acc_coa(code,name) values("9998","SUSPENSE ACCOUNT")